# Generated by Django 3.1.7 on 2021-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_text', models.TextField()),
                ('create_date', models.DateTimeField(verbose_name='date create')),
                ('update_date', models.DateTimeField(verbose_name='date update')),
                ('detail_text', models.TextField()),
                ('record_text', models.TextField()),
                ('ticket_type', models.CharField(max_length=100)),
            ],
        ),
    ]
